### ISSUE TITLE
Running ToolsBCS

### ISSUE THREAD

**Issue by Luux** [FitLayout/Builds#1]
Hi,
I'm trying to see some Box Clustering Segmentation Results. So far I maven installed/compiled all the modules, but I don't know how to use the BCS implementation yet. Building the "tools" subproject gives the runnable LayoutTools.jar where BCS isn't selectable. Both building "Builds/ToolsBCS" and "segmentation-bcs" only result in non-runnable jars.
Am I missing something there?
Thanks for your help in advance!

**Comment by radkovo** [comment]
Hello,
I am sorry for the delay. You're right, the executable JAR definition was missing in pom. I have added it just now. The executable jar should be produced by running `mvn package` in Builds/ToolsBCS.
